version: 2
updates:
- package-ecosystem: npm
  directory: "/auth"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.18
    - 5.11.19
    - 5.11.20
    - 5.12.0
    - 5.12.1
    - 5.12.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: ts-node-dev
    versions:
    - 1.1.2
    - 1.1.3
    - 1.1.4
    - 1.1.5
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
  - dependency-name: express-validator
    versions:
    - 6.10.0
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next
    versions:
    - 10.0.7
    - 10.0.9
    - 10.1.0
    - 10.1.1
    - 10.1.2
- package-ecosystem: npm
  directory: "/common"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
- package-ecosystem: npm
  directory: "/expiration"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bull
    versions:
    - 3.21.0
    - 3.21.1
    - 3.22.1
    - 3.22.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: ts-node-dev
    versions:
    - 1.1.2
    - 1.1.3
    - 1.1.4
    - 1.1.5
  - dependency-name: typescript
    versions:
    - 3.9.8
- package-ecosystem: npm
  directory: "/orders"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.11.20
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: "@types/jsonwebtoken"
    versions:
    - 8.5.1
  - dependency-name: ts-node-dev
    versions:
    - 1.1.2
    - 1.1.3
    - 1.1.4
    - 1.1.5
  - dependency-name: express-validator
    versions:
    - 6.10.0
  - dependency-name: typescript
    versions:
    - 3.9.8
  - dependency-name: supertest
    versions:
    - 6.1.3
- package-ecosystem: npm
  directory: "/payments"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: stripe
    versions:
    - 8.133.0
    - 8.136.0
    - 8.138.0
    - 8.139.0
    - 8.141.0
    - 8.143.0
    - 8.145.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/supertest"
    versions:
    - 2.0.11
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.18
    - 5.11.20
    - 5.12.0
    - 5.12.1
    - 5.12.2
  - dependency-name: ts-node-dev
    versions:
    - 1.1.2
    - 1.1.3
    - 1.1.4
    - 1.1.5
    - 1.1.6
  - dependency-name: typescript
    versions:
    - 3.9.8
- package-ecosystem: npm
  directory: "/tickets"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/mongoose"
    versions:
    - 5.10.4
    - 5.10.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.18
    - 5.11.20
    - 5.12.0
    - 5.12.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: ts-node-dev
    versions:
    - 1.1.2
    - 1.1.3
    - 1.1.4
    - 1.1.5
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
  - dependency-name: express-validator
    versions:
    - 6.10.0
